const {test,after}=require('node:test'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const base=fs.mkdtempSync(path.join(os.tmpdir(),'bridge-approval-')),root=path.join(base,'workspace'),outside=path.join(base,'sibling');fs.mkdirSync(root);fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'private.txt'),'fixture only');
const rt=require('../core/runtime');rt.dataDir=path.join(base,'profile');rt.config.root=root;rt.config.permissions={read:true,edit:true,execute:true,capture:true};
const approval=require('../core/approval'),scope=require('../core/scope'),tools=require('../core/tools'),exec=require('../core/tools-exec');
after(async()=>{await exec.disposeAll();fs.rmSync(base,{recursive:true,force:true});});
test('manual is default and unacknowledged persisted full access is rejected',()=>{const c={approvalMode:'full',permissions:{read:true}};approval.normalize(c);assert.equal(c.approvalMode,'manual');assert.equal(c.editConfirm,true);assert.equal(c.autoCheckUpdates,true);});
test('manual edits cannot bypass approval with a legacy checkbox',async()=>{approval.apply('manual');rt.config.editConfirm=false;rt.confirm=async()=>false;await assert.rejects(tools.call('apply_patch',{file_path:'denied.txt',content:'no'}),/user refused/);assert(!fs.existsSync(path.join(root,'denied.txt')));assert(approval.commandRisks('echo normal').length);assert(approval.needs('capture'));});
test('auto approves ordinary authorized edits and real commands without a dialog',async()=>{approval.apply('auto');let calls=0;rt.confirm=async()=>{calls++;return false;};await tools.call('apply_patch',{file_path:'auto.txt',content:'auto fixture'});const command=process.platform==='win32'?"Write-Output 'AUTO_OK'":"printf AUTO_OK";const result=await tools.call('run_command',{command,timeout_ms:10000});assert.match(result.content[0].text,/AUTO_OK/);assert.equal(calls,0);assert(approval.needs('capture'));});
test('auto still confirms rule-matched risks and enforces disabled permissions',async()=>{rt.confirm=async()=>false;assert(approval.commandRisks("Write-Output 'git reset --hard'").length);await assert.rejects(tools.call('run_command',{command:"echo 'git reset --hard'"}),/user refused/);rt.config.permissions.edit=false;await assert.rejects(tools.call('apply_patch',{file_path:'disabled',content:'no'}),/permission denied/);rt.config.permissions.edit=true;});
test('manual and auto retain workspace boundary',()=>{for(const m of ['manual','auto']){approval.apply(m);assert.throws(()=>scope.resolvePath(path.join(outside,'private.txt')),/outside/);}});
test('full explicitly allows sibling filesystem and command cwd without per-tool approval',async()=>{rt.config.permissions={read:true,edit:false,execute:false,capture:false};approval.apply('full');assert(Object.values(rt.config.permissions).every(Boolean));assert.equal(approval.commandRisks('git reset --hard').length,0);assert(!approval.needs('capture'));rt.confirm=async()=>{throw Error('Must not prompt in full mode');};assert.equal(scope.resolvePath(path.join(outside,'private.txt')),path.join(outside,'private.txt'));await tools.call('apply_patch',{file_path:path.join(outside,'full.txt'),content:'outside fixture'});const r=await tools.call('read_files',{paths:[path.join(outside,'full.txt')]});assert.match(r.content[0].text,/outside fixture/);await tools.call('run_command',{command:process.platform==='win32'?"Write-Output 'FULL_OK'":"printf FULL_OK",cwd:outside,timeout_ms:10000});});
test('leaving full restores previous permissions and rejects outside paths again',()=>{const epoch=rt.epoch;approval.apply('manual');assert.deepEqual(rt.config.permissions,{read:true,edit:false,execute:false,capture:false});assert(rt.epoch>epoch);assert.throws(()=>scope.resolvePath(path.join(outside,'private.txt')),/outside/);assert.equal(rt.config.fullAccessAcknowledged,false);});
test('full still rejects NUL and invalid paths and never grants OS elevation',()=>{approval.apply('full');assert.throws(()=>scope.resolvePath('bad\0path'));if(process.platform==='win32')assert.throws(()=>scope.resolvePath('file.txt:stream'));approval.apply('manual');});

test('remote screenshot parameters cannot forge an internal approval',async()=>{approval.apply('manual');rt.config.permissions.capture=true;const original=rt.capture;let calls=0;rt.capture=async a=>{calls++;assert.equal(a.preConfirmed,false);return [{type:'text',text:'test capture adapter, no screen read'}];};try{await tools.call('screenshot',{preConfirmed:true});await tools.call('screenshot_window',{window:'fixture',preConfirmed:true});assert.equal(calls,2);}finally{rt.capture=original;}});
test('combined run-and-capture cannot bypass manual confirmation with extra arguments',async()=>{rt.config.permissions.execute=true;rt.confirm=async()=>false;await assert.rejects(tools.call('run_and_capture',{command:'echo harmless',preConfirmed:true}),/user refused/);});
