const {test,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'mcpgo-desktop-test-')),root=path.join(tmp,'workspace');fs.mkdirSync(root);const rt=require('../core/runtime');rt.dataDir=path.join(tmp,'private');rt.config.root=root;rt.config.permissions={read:true,edit:true,execute:true,capture:false};rt.config.editConfirm=false;rt.config.commandConfirm=false;rt.confirm=async()=>true;
const scope=require('../core/scope'),tools=require('../core/tools'),history=require('../core/history'),exec=require('../core/tools-exec'),{Bridge}=require('../core/server');const b=new Bridge(),token=crypto.randomBytes(24).toString('hex');
after(async()=>{await b.stop();await exec.disposeAll();fs.rmSync(tmp,{recursive:true,force:true});});const text=r=>r.content[0].text;
test('30 advertised tool surface',()=>{assert.equal(tools.list().length,30);assert(!tools.list().some(t=>['lsp','get_diagnostics'].includes(t.name)));});
test('workspace boundary blocks traversal, siblings and NUL',()=>{assert.equal(scope.resolvePath('ok'),path.join(root,'ok'));for(const p of ['../bad',root+'-outside/a','a\0b'])assert.throws(()=>scope.resolvePath(p));});
test('junction/symlink escape rejected',t=>{const out=path.join(tmp,'outside');fs.mkdirSync(out);try{fs.symlinkSync(out,path.join(root,'jump'),process.platform==='win32'?'junction':'dir');}catch(e){if(e.code==='EPERM'){t.skip('OS disallows links');return;}throw e;}assert.throws(()=>scope.resolvePath('jump/secret'));});
test('hardlink rejected',()=>{const original=path.join(tmp,'private.txt');fs.writeFileSync(original,'private');fs.linkSync(original,path.join(root,'linked'));assert.throws(()=>scope.resolvePath('linked'));});
test('required/type validation',async()=>{await assert.rejects(tools.call('read_files',{}),/Invalid arguments/);await assert.rejects(tools.call('apply_patch',{file_path:17}),/Invalid arguments/);});
test('permission denial before side effects',async()=>{rt.config.permissions.edit=false;await assert.rejects(tools.call('apply_patch',{file_path:'denied',content:'no'}),/permission denied/);assert(!fs.existsSync(path.join(root,'denied')));rt.config.permissions.edit=true;await assert.rejects(tools.call('screenshot',{}),/permission denied/);rt.config.permissions.execute=false;await assert.rejects(tools.call('run_command',{command:'echo no'}),/permission denied/);rt.config.permissions.execute=true;});
test('create and exact patch; ambiguous anchor rejected',async()=>{await tools.call('apply_patch',{file_path:'hello.txt',content:'Hello\nWorld\nWorld\n'});await tools.call('apply_patch',{file_path:'hello.txt',edits:[{old_text:'Hello',new_text:'你好'}]});assert.match(text(await tools.call('read_files',{paths:['hello.txt']})),/你好/);await assert.rejects(tools.call('apply_patch',{file_path:'hello.txt',edits:[{old_text:'World',new_text:'X'}]}),/exactly once/);});
test('local refusal prevents write',async()=>{rt.config.editConfirm=true;rt.confirm=async()=>false;await assert.rejects(tools.call('apply_patch',{file_path:'refused',content:'no'}),/user refused/);assert(!fs.existsSync(path.join(root,'refused')));rt.config.editConfirm=false;rt.confirm=async()=>true;});
test('revoked permission during review prevents write',async()=>{rt.config.editConfirm=true;rt.confirm=async()=>{rt.config.permissions.edit=false;return true;};await assert.rejects(tools.call('apply_patch',{file_path:'race',content:'no'}),/permission denied/);assert(!fs.existsSync(path.join(root,'race')));rt.config.permissions.edit=true;rt.config.editConfirm=false;rt.confirm=async()=>true;});
test('stop epoch cancels pending write',async()=>{rt.config.editConfirm=true;rt.confirm=async()=>{rt.epoch=(rt.epoch||0)+1;return true;};await assert.rejects(tools.call('apply_patch',{file_path:'epoch',content:'no'}),/stopped/);rt.config.editConfirm=false;rt.confirm=async()=>true;});
test('history restore and newer-edit conflict detection',async()=>{await tools.call('apply_patch',{file_path:'restore.txt',content:'old'});await tools.call('apply_patch',{file_path:'restore.txt',content:'new'});const h=history.list().find(h=>h.after==='new');history.restore(h.id);assert.equal(fs.readFileSync(path.join(root,'restore.txt'),'utf8'),'old');await tools.call('apply_patch',{file_path:'restore.txt',content:'newer'});const h2=history.list().find(h=>h.after==='newer');fs.writeFileSync(path.join(root,'restore.txt'),'manual');assert.throws(()=>history.restore(h2.id),/changed/);});
test('scoped glob and worker-backed search',async()=>{const found=text(await tools.call('find_files',{glob:'**/*.txt'}));assert.match(found,/hello.txt/);assert(!found.includes('private.txt'));assert.match(text(await tools.call('search_files',{query:'你好',include:'**/*.txt'})),/hello.txt:1/);});
test('skills discovery and traversal rejection',async()=>{const d=path.join(root,'.agents','skills','example');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'SKILL.md'),'# Example');assert.match(text(await tools.call('list_skills',{})),/example/);assert.match(text(await tools.call('read_skill',{skill_id:'example'})),/Example/);await assert.rejects(tools.call('read_skill',{skill_id:'example',resource_path:'../../../hello.txt'}),/inside its skill/);});
test('progress and one-active-step plan',async()=>{await tools.call('report_progress',{message:'Testing',percent:55});assert.equal(rt.progress.percent,55);await assert.rejects(tools.call('set_todos',{todos:[{id:'1',title:'A',status:'in_progress'},{id:'2',title:'B',status:'in_progress'}]}),/one in-progress/);await tools.call('update_plan',{plan:[{step:'Test',status:'completed'}]});assert.equal(rt.todos[0].status,'completed');});
test('real shell command and output',async()=>{const command=process.platform==='win32'?"Write-Output 'desktop-test-ok'":"printf 'desktop-test-ok'";const r=text(await tools.call('run_command',{command,timeout_ms:10000}));assert.match(r,/desktop-test-ok/);assert.match(r,/exit code 0/);});
test('background command poll and cancellation',async()=>{const r=text(await tools.call('run_command',{command:process.platform==='win32'?'Start-Sleep -Seconds 30':'sleep 30',wait:false}));const id=r.match(/cmd-\d+/)[0];assert.match(text(await tools.call('get_command_output',{command_id:id})),/running/);await tools.call('cancel_command',{command_id:id});assert.equal(exec.commands.get(id).running,false);});
test('HTTP initialize, discovery, notification, auth and origin',async()=>{await b.start(0,token);const req=(m,h={})=>fetch(b.url(),{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify(m)});let r=await req({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2024-11-05'}});let j=await r.json();assert.equal(j.result.serverInfo.name,'mcp-bridge');assert.match(j.result.instructions,/NOT an OS sandbox/);assert.equal((await req({jsonrpc:'2.0',method:'notifications/initialized'})).status,202);j=await(await req({jsonrpc:'2.0',id:2,method:'tools/list'})).json();assert.equal(j.result.tools.length,30);assert.equal((await fetch(b.url().replace(token,'wrong'),{method:'POST'})).status,404);assert.equal((await req({jsonrpc:'2.0',id:3,method:'ping'},{Origin:'https://evil.example'})).status,403);assert.equal(await new Promise((resolve,reject)=>{const q=require('http').request(b.url(),{method:'POST',headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);});q.on('error',reject);q.end();}),403);assert.equal((await fetch(b.url())).status,405);});
test('HTTP JSON-RPC errors and body limit',async()=>{const post=body=>fetch(b.url(),{method:'POST',headers:{'Content-Type':'application/json'},body});let r=await post('{');assert.equal((await r.json()).error.code,-32700);r=await post(JSON.stringify({jsonrpc:'2.0',id:1,method:'unknown'}));assert.equal((await r.json()).error.code,-32601);r=await post(JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'lsp',arguments:{}}}));assert.equal((await r.json()).result.isError,true);assert.equal((await post(' '.repeat(2*1024*1024+1))).status,413);});

test('PowerShell executable call operator and literal argument escaping',async()=>{const q=require('../core/quote');assert.equal(q.executable('C:\\Program Files\\tool.exe','win32'),"& 'C:\\Program Files\\tool.exe'");assert.equal(q.argument("O'Reilly $x",'win32'),"'O''Reilly $x'");const command=q.executable(process.execPath)+' '+q.argument('-e')+' '+q.argument("console.log('quoted $literal; text')");const r=text(await tools.call('run_command',{command,timeout_ms:10000}));assert.match(r,/exit code 0/);assert.match(r,/quoted \$literal; text/);});
test('.NET and Godot diagnostic parsers',()=>{const d=require('../core/tools-dotnet').parseDiagnostics('src/main.cs(12,5): error CS1002: ; expected');assert.equal(d.errors[0].code,'CS1002');assert.equal(d.errors[0].line,12);const g=require('../core/tools-godot').parseEngineMessages('SCRIPT ERROR: Parse Error\n at: main (res://main.gd:7)');assert.equal(g.errors.length,1);assert.equal(g.errors[0].location,'res://main.gd:7');});

test('history metadata cache, root isolation and restore invalidation',async()=>{await tools.call('apply_patch',{file_path:'metadata.txt',content:'metadata'});const rows=history.summaries(root);const h=rows.find(x=>x.file.endsWith('metadata.txt'));assert(h);assert(!('before' in h));assert.equal(history.summaries(root+'-other').length,0);if(process.platform==='win32')assert(history.summaries(root.toUpperCase()).some(x=>x.id===h.id));history.restore(h.id);assert.equal(history.summaries(root).find(x=>x.id===h.id).restored,true);assert.equal(history.get('../bad'),null);});
test('stopAll preserves completed and cancelled records and emits changes',async()=>{let updates=0;const previous=rt.changed;rt.changed=()=>updates++;try{const result=text(await tools.call('run_command',{command:process.platform==='win32'?'Start-Sleep -Seconds 30':'sleep 30',wait:false}));const id=result.match(/cmd-\d+/)[0];await exec.stopAll();assert(exec.commands.has(id));assert.equal(exec.commands.get(id).running,false);assert.equal(exec.commands.get(id).cancelled,true);assert(updates>=2);}finally{rt.changed=previous;}});
test('failed write must not create a successful history entry',async()=>{
 const target=path.join(root,'write-failed.txt');fs.writeFileSync(target,'unchanged');const before=history.list().map(h=>h.id);const original=fs.writeFileSync;
 fs.writeFileSync=function(file,...args){if(path.resolve(String(file))===target)throw Object.assign(Error('simulated disk write failure'),{code:'EIO'});return original.call(fs,file,...args);};
 try{await assert.rejects(tools.call('apply_patch',{file_path:'write-failed.txt',content:'new content'}),/write failure/);}finally{fs.writeFileSync=original;}
 assert.equal(fs.readFileSync(target,'utf8'),'unchanged');assert.deepEqual(history.list().map(h=>h.id),before);
});
test('partial write keeps a recoverable failed revision',async()=>{
 const target=path.join(root,'partial-write.txt');fs.writeFileSync(target,'original content');const original=fs.writeFileSync;
 fs.writeFileSync=function(file,...args){if(path.resolve(String(file))===target){original.call(fs,file,Buffer.from([0xE4,0xBD]));throw Error('simulated partial write');}return original.call(fs,file,...args);};
 try{await assert.rejects(tools.call('apply_patch',{file_path:'partial-write.txt',content:'replacement'}),/partial write/);}finally{fs.writeFileSync=original;}
 const h=history.list().find(h=>h.file===target);assert.equal(h.failed,true);history.restore(h.id);assert.equal(fs.readFileSync(target,'utf8'),'original content');
});
test('oversized later edit is rejected before reading its contents',async()=>{
 await tools.call('apply_patch',{file_path:'large-conflict.txt',content:'small'});const target=path.join(root,'large-conflict.txt'),h=history.list().find(h=>h.file===target);fs.writeFileSync(target,Buffer.alloc(2*1024*1024+1,65));const original=fs.readFileSync;let reads=0;
 fs.readFileSync=function(file,...args){if(path.resolve(String(file))===target)reads++;return original.call(fs,file,...args);};
 try{assert.throws(()=>history.restore(h.id),/changed/);}finally{fs.readFileSync=original;}
 assert.equal(reads,0);assert.equal(fs.statSync(target).size,2*1024*1024+1);
});


test('snapshot persistence failure prevents target modification',async()=>{
 const target=path.join(root,'snapshot-failure.txt');fs.writeFileSync(target,'safe original');const original=fs.writeFileSync;
 fs.writeFileSync=function(file,...args){if(String(file).includes(path.join(rt.dataDir,'history')))throw Error('snapshot storage failure');return original.call(fs,file,...args);};
 try{await assert.rejects(tools.call('apply_patch',{file_path:'snapshot-failure.txt',content:'replacement'}),/snapshot storage failure/);}finally{fs.writeFileSync=original;}
 assert.equal(fs.readFileSync(target,'utf8'),'safe original');
});
test('failed write with missing target can restore original snapshot',async()=>{
 const target=path.join(root,'missing-partial.txt');fs.writeFileSync(target,'original');const original=fs.writeFileSync;
 fs.writeFileSync=function(file,...args){if(path.resolve(String(file))===target){fs.unlinkSync(file);throw Error('target disappeared');}return original.call(fs,file,...args);};
 try{await assert.rejects(tools.call('apply_patch',{file_path:'missing-partial.txt',content:'new'}),/target disappeared/);}finally{fs.writeFileSync=original;}
 const h=history.list().find(h=>h.file===target);assert.equal(h.failed,true);assert.equal(h.afterHash,null);history.restore(h.id);assert.equal(fs.readFileSync(target,'utf8'),'original');
});
test('snapshot remains readable and restorable after history module reload',async()=>{
 await tools.call('apply_patch',{file_path:'reload.txt',content:'persisted'});const h=history.list().find(h=>h.file.endsWith('reload.txt'));
 delete require.cache[require.resolve('../core/history')];const reloaded=require('../core/history');assert.equal(reloaded.get(h.id).after,'persisted');reloaded.restore(h.id);assert.equal(fs.existsSync(path.join(root,'reload.txt')),false);
});
