const {test,after}=require('node:test'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{Readable}=require('stream');
const {Updater,select,newer,safeURL}=require('../main/updater.cjs');const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'bridge-updater-'));after(()=>fs.rmSync(tmp,{recursive:true,force:true}));let serial=0;
const body=Buffer.from('MZ fixture installer - never executed');
function release(data=body){return {tag_name:'v1.3.0',draft:false,prerelease:false,html_url:'https://github.com/cnrpot/mcp-bridge/releases/tag/v1.3.0',assets:[{name:'mcp-bridge-1.3.0-Setup-x64.exe',state:'uploaded',size:data.length,digest:'sha256:'+crypto.createHash('sha256').update(data).digest('hex'),browser_download_url:'https://github.com/cnrpot/mcp-bridge/releases/download/v1.3.0/mcp-bridge-1.3.0-Setup-x64.exe'}]};}
function make(options={}){return new Updater({currentVersion:'1.2.0',dataDir:path.join(tmp,String(serial++)),platform:'win32',arch:'x64',transport:{getJSON:async()=>release(),open:async()=>{const r=Readable.from([body.subarray(0,5),body.subarray(5)]);r.headers={'content-length':String(body.length)};return r;}},...options});}
test('stable numeric versions compare correctly without downgrades or prerelease updates',()=>{assert(newer('v1.10.0','1.2.0'));assert(!newer('1.2.0','1.2.0'));assert(!newer('1.1.1','1.2.0'));assert(!newer('1.3.0-beta','1.2.0'));assert.equal(select({...release(),prerelease:true},'1.2.0'),null);assert.equal(select(release(),'1.3.0'),null);});
test('only exact GitHub repository asset URLs, hashes and sane sizes accepted',()=>{const r=release();r.assets[0].browser_download_url='https://evil.example/update.exe';assert.throws(()=>select(r,'1.2.0'));for(const a of [{digest:null},{size:900*1024*1024},{name:'other.exe'}]){const r=release();Object.assign(r.assets[0],a);assert.throws(()=>select(r,'1.2.0'));}const r2=release();r2.assets.push({...r2.assets[0]});assert.throws(()=>select(r2,'1.2.0'));});
test('redirect validation never permits plaintext, credentials or arbitrary hosts',()=>{for(const url of ['http://github.com/a','https://github.com.evil.example/a','https://user:secret@github.com/a','https://127.0.0.1/a','https://github.com:444/a'])assert.throws(()=>safeURL(url));assert.equal(safeURL('https://release-assets.githubusercontent.com/a').protocol,'https:');});
test('check only finds updates; never downloads automatically',async()=>{let opens=0;const u=make({transport:{getJSON:async()=>release(),open:async()=>{opens++;throw Error('not requested');}}});await u.check();assert.equal(u.state.status,'available');assert.equal(opens,0);assert.equal(u.file,null);});
test('streamed download reports progress, verifies SHA256 and rechecks before installation',async()=>{const states=[];const u=make({onChange:()=>states.push(u.snapshot())});await u.check();await u.download();assert.equal(u.state.status,'ready');assert.equal(u.state.progress,100);assert.equal(fs.readFileSync(await u.prepareInstall()).equals(body),true);assert(states.some(s=>s.status==='downloading'));assert(!fs.readdirSync(u.dir).some(n=>n.endsWith('.part')));});
test('hash mismatch refuses file and removes partial downloads',async()=>{const u=make({transport:{getJSON:async()=>release(),open:async()=>Readable.from([Buffer.alloc(body.length,65)])}});await u.check();await assert.rejects(u.download(),/SHA256/);assert.equal(u.state.status,'error');assert.equal(u.file,null);assert.deepEqual(fs.readdirSync(u.dir),[]);});
test('oversized and truncated downloads are rejected',async()=>{for(const data of [Buffer.concat([body,body]),body.subarray(0,5)]){const u=make({transport:{getJSON:async()=>release(),open:async()=>Readable.from([data])}});await u.check();await assert.rejects(u.download());assert.equal(u.file,null);assert.deepEqual(fs.readdirSync(u.dir),[]);}});
test('tampering after successful download prevents install',async()=>{const u=make();await u.check();await u.download();fs.writeFileSync(u.file,Buffer.alloc(body.length,66));await assert.rejects(u.prepareInstall(),/校验失败/);assert.equal(u.state.status,'error');});
test('download cancellation removes partial data and can be retried',async()=>{const u=make({transport:{getJSON:async()=>release(),open:async()=>Readable.from((async function*(){yield body.subarray(0,5);await new Promise(r=>setTimeout(r,80));yield body.subarray(5);})())}});await u.check();const p=u.download();setTimeout(()=>u.cancel(),15);await assert.rejects(p);assert.equal(u.file,null);assert.deepEqual(fs.readdirSync(u.dir),[]);await u.download();assert.equal(u.state.status,'ready');});
test('parallel checks/downloads rejected; unsupported platform cannot download',async()=>{let finish;const u=make({transport:{getJSON:()=>new Promise(r=>finish=r)}});const pending=u.check();await assert.rejects(u.check(),/正在进行/);await assert.rejects(u.download(),/正在进行/);finish(release());await pending;const other=make({platform:'linux'});await other.check();await assert.rejects(other.download(),/Windows/);});
test('API failure does not retain a stale update candidate',async()=>{const u=make();await u.check();u.transport.getJSON=async()=>{throw Error('offline');};await assert.rejects(u.check(),/offline/);assert.equal(u.candidate,null);assert.equal(u.state.version,null);await assert.rejects(u.download(),/先检查/);});
