// Explicit, isolated developer test. No real screenshot capture or installer execution.
module.exports=async({win,action,bridge,rt,app,updater})=>{
 const fs=require('fs'),path=require('path'),assert=require('assert/strict'),http=require('http'),crypto=require('crypto'),{dialog}=require('electron');
 const base=process.env.MCPGO_DESKTOP_SMOKE_DIR,checks=[],original=dialog.showMessageBox,originalTransport=updater.transport;let fixture,allow=true;const prompts=[];
 const delay=ms=>new Promise(r=>setTimeout(r,ms)),js=c=>win.webContents.executeJavaScript(c);
 const until=async(fn,label)=>{for(let i=0;i<150;i++){if(await fn())return;await delay(100);}throw Error('Timeout: '+label);};
 const click=s=>js(`document.querySelector(${JSON.stringify(s)}).click();true`);
 const shot=async n=>{win.show();win.focus();await delay(350);fs.writeFileSync(path.join(base,n+'.png'),(await win.webContents.capturePage()).toPNG());};
 try{
  assert(base&&path.isAbsolute(base));fs.mkdirSync(base,{recursive:true});const root=path.join(base,'workspace'),outside=path.join(base,'outside');fs.mkdirSync(root,{recursive:true});fs.mkdirSync(outside,{recursive:true});fs.writeFileSync(path.join(outside,'fixture.txt'),'outside fixture');
  rt.config.root=root;rt.config.port=18795;rt.config.tunnelProvider='none';rt.changed();
  dialog.showMessageBox=async(_win,o)=>{prompts.push(o);return {response:allow?1:0};};
  const errors=[];win.webContents.on('console-message',(d,l,m)=>{if((d.level??l)==='error'||(d.level??l)===3)errors.push(d.message??m);});
  await action('settings',{permissions:{edit:true,execute:true}});await action('start');
  const rpc=async(method,params={})=>{const r=await fetch(bridge.url(),{method:'POST',headers:{'Content-Type':'application/json','Connection':'close'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});assert.equal(r.status,200);return (await r.json()).result;};
  await rpc('initialize');await fetch(bridge.url(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})});await rpc('tools/list');
  const tool=async(name,args)=>{const r=await rpc('tools/call',{name,arguments:args});assert(!r.isError,JSON.stringify(r));return r.content[0].text;};await tool('list_skills',{});
  const choose=async(mode,accepted=true)=>{allow=accepted;const prior=(await action('state')).config.approvalMode,start=prompts.length;await js(`document.querySelector('#approvalMode').value=${JSON.stringify(mode)};document.querySelector('#approvalMode').dispatchEvent(new Event('change'));true`);if(mode!=='manual')await until(()=>prompts.length>start,'mode confirmation');await until(async()=>{const s=await action('state');return !s.modeChanging&&s.config.approvalMode===(accepted?mode:prior);},'mode applied');allow=true;};
  await choose('full',false);assert.equal((await action('state')).config.approvalMode,'manual');assert.equal((await action('state')).config.permissions.capture,false);checks.push('full-access refusal leaves mode and permissions unchanged');
  let count=prompts.length;await tool('apply_patch',{file_path:'manual.txt',content:'manual fixture'});assert.equal(prompts.length,count+1);await tool('run_command',{command:'Write-Output "MANUAL_OK"',timeout_ms:10000});assert.equal(prompts.length,count+2);checks.push('manual mode confirms actual file edit and command');
  await choose('auto');count=prompts.length;await tool('read_files',{paths:['manual.txt']});await tool('apply_patch',{file_path:'manual.txt',content:'auto fixture'});await tool('run_command',{command:'Write-Output "AUTO_OK"',timeout_ms:10000});assert.equal(prompts.length,count);checks.push('auto mode performs authorized ordinary operations without dialogs');
  allow=false;const risk=await rpc('tools/call',{name:'run_command',arguments:{command:"Write-Output 'git reset --hard'"}});allow=true;assert.equal(risk.isError,true);assert.equal(prompts.length,count+1);checks.push('auto mode still asks for rule-matched command risk');
  const outsidePath=path.join(outside,'fixture.txt');const blocked=await tool('read_files',{paths:[outsidePath]});assert.match(blocked,/\[ERROR\]/);assert(!blocked.includes('outside fixture'));const beforeFull={...(await action('state')).config.permissions};await choose('full');count=prompts.length;
  assert.match(await tool('read_files',{paths:[outsidePath]}),/outside fixture/);await tool('apply_patch',{file_path:outsidePath,content:'full access fixture'});await tool('run_command',{command:'Write-Output "FULL_OK"',cwd:outside,timeout_ms:10000});assert.equal(prompts.length,count);assert(Object.values((await action('state')).config.permissions).every(Boolean));checks.push('confirmed full access reads/writes sibling fixture and runs outside cwd without per-tool dialogs');
  await until(()=>js("document.querySelector('#approvalBadge').textContent==='完全访问'"),'full badge');await shot('full-access');
  await choose('manual');assert.deepEqual((await action('state')).config.permissions,beforeFull);const denied=await tool('read_files',{paths:[outsidePath]});assert.match(denied,/outside/);assert(!denied.includes('full access fixture'));checks.push('leaving full restores permissions and workspace boundary');
  const body=Buffer.concat([Buffer.from('MZ'),Buffer.alloc(512*1024,65)]),release={tag_name:'v9.0.0',draft:false,prerelease:false,html_url:'https://github.com/cnrpot/mcp-bridge/releases/tag/v9.0.0',assets:[{name:'mcp-bridge-9.0.0-Setup-x64.exe',state:'uploaded',size:body.length,digest:'sha256:'+crypto.createHash('sha256').update(body).digest('hex'),browser_download_url:'https://github.com/cnrpot/mcp-bridge/releases/download/v9.0.0/mcp-bridge-9.0.0-Setup-x64.exe'}]};
  let downloads=0;fixture=http.createServer((req,res)=>{if(req.url==='/metadata'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(release));}downloads++;res.setHeader('Content-Length',body.length);let offset=0;const timer=setInterval(()=>{const next=Math.min(offset+16384,body.length);res.write(body.subarray(offset,next));offset=next;if(offset===body.length){clearInterval(timer);res.end();}},25);res.on('close',()=>clearInterval(timer));});await new Promise(r=>fixture.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+fixture.address().port;
  updater.transport={getJSON:async(_url,signal)=>(await fetch(url+'/metadata',{signal})).json(),open:(_url,signal)=>new Promise((resolve,reject)=>{http.get(url+'/installer',{signal},resolve).on('error',reject);})};
  await click('[data-view=settings]');await click('#checkUpdates');await until(()=>updater.state.status==='available','update found');assert.equal(downloads,0);await until(()=>js("document.querySelector('#updateStatus').textContent.includes('9.0.0')"),'version displayed');await until(()=>js("!document.querySelector('#updateNotice').classList.contains('hidden')"),'global update notice');checks.push('update check displays fixture version and global notice without automatically downloading');
  await click('#downloadUpdate');await until(()=>updater.state.status==='downloading','download begins');await until(()=>updater.state.status==='ready','verified download completes');assert.equal(downloads,1);assert.equal(fs.statSync(updater.file).size,body.length);await until(()=>js("document.querySelector('#updateStatus').textContent.includes('SHA256')"),'ready state visible');checks.push('manual download streams over real fixture HTTP and updates progress/verified state');
  const started=await tool('run_command',{command:'Start-Sleep -Seconds 30',wait:false});const id=started.match(/cmd-\d+/)[0];await until(()=>js("document.querySelector('#installUpdate').disabled"),'install disabled during job');if(app.isPackaged)await assert.rejects(action('installUpdate'),/运行任务/);await action('cancelJob',{id});checks.push('running task blocks update installation');
  if(app.isPackaged){allow=false;assert.equal(await action('installUpdate'),false);allow=true;assert.equal(updater.state.status,'ready');checks.push('declining install confirmation does not launch installer or quit');}else{await assert.rejects(action('installUpdate'),/打包后/);checks.push('development mode cannot launch installer');}
  fs.writeFileSync(updater.file,Buffer.alloc(body.length,66));await assert.rejects(updater.prepareInstall(),/校验失败/);await until(()=>js("document.querySelector('#installUpdate').disabled"),'tampering disables installation');checks.push('post-download tampering is rejected and disables install');
  await js("document.querySelector('#autoCheckUpdates').checked=false;document.querySelector('#autoCheckUpdates').dispatchEvent(new Event('change'));true");await until(async()=>(await action('state')).config.autoCheckUpdates===false,'auto-check toggle saved');const settings=JSON.parse(fs.readFileSync(path.join(rt.dataDir,'settings.json'),'utf8'));assert.equal(settings.autoCheckUpdates,false);checks.push('automatic checking preference persists without permission changes');
  updater.transport=originalTransport;updater.candidate=null;updater.file=null;updater.set({status:'idle',version:null,error:'',progress:0});await shot('update-settings');assert.equal(errors.length,0,errors.join(';'));checks.push('renderer has no unexpected errors');
  await new Promise(r=>fixture.close(r));fixture=null;dialog.showMessageBox=original;
  fs.writeFileSync(path.join(base,'feature-result.json'),JSON.stringify({ok:true,version:app.getVersion(),packaged:app.isPackaged,checks,confirmationMode:'Isolated test automatically answers native confirmation API; fake MZ fixture never executed'},null,2));console.log('FEATURE_TEST_OK '+checks.length);app.quit();
 }catch(e){dialog.showMessageBox=original;updater.transport=originalTransport;fixture?.close();fs.mkdirSync(base,{recursive:true});fs.writeFileSync(path.join(base,'feature-result.json'),JSON.stringify({ok:false,checks,error:e.stack},null,2));console.error(e.stack);app.exit(1);}
};
