// Local, explicit test launcher only. Uses an isolated profile and fixture workspace.
module.exports=async({win,action,bridge,rt,app})=>{
 const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{dialog}=require('electron');
 const base=process.env.MCPGO_DESKTOP_SMOKE_DIR,checks=[],confirmations=[];const original=dialog.showMessageBox,originalOpen=dialog.showOpenDialog;
 const delay=ms=>new Promise(r=>setTimeout(r,ms));
 const js=code=>win.webContents.executeJavaScript(code);
 const until=async(fn,label)=>{const end=Date.now()+15000;while(Date.now()<end){if(await fn())return;await delay(100);}throw Error('Timed out: '+label);};
 const click=selector=>js(`document.querySelector(${JSON.stringify(selector)}).click();true`);
 const dom=selector=>js(`document.querySelector(${JSON.stringify(selector)})?.textContent||''`);
 const shot=async name=>{win.show();win.focus();await delay(500);fs.writeFileSync(path.join(base,name+'.png'),(await win.webContents.capturePage()).toPNG());};
 try{
  assert(base&&path.isAbsolute(base));assert(process.env.MCPGO_DESKTOP_TEST_DATA);fs.mkdirSync(base,{recursive:true});
  const root=path.join(base,'workspace');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'fixture.txt'),'before-flow\n');
  rt.config.root=process.platform==='win32'?root.toLowerCase():root;rt.config.port=18791;rt.config.tunnelProvider='none';rt.changed();
  const errors=[];win.webContents.on('console-message',(d,l,m)=>{if((d.level??l)==='error'||(d.level??l)===3)errors.push(d.message??m);});
  await until(async()=>!(await js("document.querySelector('#startStop').disabled")),'start enabled');await click('#startStop');await until(()=>!!bridge.server,'real server start');
  const rpc=async(method,params={})=>{const r=await fetch(bridge.url(),{method:'POST',headers:{'Content-Type':'application/json','Connection':'close'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});assert.equal(r.status,200);return (await r.json()).result;};
  const tool=async(name,args)=>{const r=await rpc('tools/call',{name,arguments:args});assert(!r.isError,JSON.stringify(r));return r.content[0].text;};
  assert.equal((await rpc('initialize')).serverInfo.name,'mcp-bridge');assert.equal((await fetch(bridge.url(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})})).status,202);assert.equal((await rpc('tools/list')).tools.length,30);assert.equal(await js('document.title'),'mcp-bridge');assert(!/VS Code|vscode|移植|迁移/i.test(await dom('body')));checks.push('brand, MCP initialization and 30-tool discovery');
  assert((await rpc('tools/call',{name:'run_command',arguments:{command:'echo forbidden'}})).isError);checks.push('Execute denied by default');
  // Automate native confirmation responses ONLY in this isolated fixture process.
  dialog.showMessageBox=async(_win,options)=>{confirmations.push({title:options.title,message:options.message});return {response:1};};
  await action('settings',{permissions:{execute:true,edit:true}});await click('[data-view="jobs"]');
  const first=await tool('run_command',{command:'Write-Output "FLOW_READY"; $v=[Console]::ReadLine(); Write-Output ("FLOW_INPUT:"+$v); Start-Sleep -Milliseconds 1300; Write-Output "FLOW_DONE"',wait:false});const id=first.match(/cmd-\d+/)[0];
  await until(async()=>/运行中/.test(await js(`document.querySelector('[data-job="${id}"]')?.closest('.job').textContent||''`)),'running job automatically rendered');checks.push('real background task appears as running without manual refresh');
  await click(`[data-job="${id}"]`);await until(async()=>/FLOW_READY/.test(await dom('#liveJobOutput')),'live initial output');
  await js("document.querySelector('#jobInput').value='fixture-input';document.querySelector('#sendInput').click();true");
  await until(async()=>/FLOW_INPUT:fixture-input/.test(await dom('#liveJobOutput')),'actual stdin echoed');await until(async()=>/FLOW_DONE/.test(await dom('#liveJobOutput')),'live final output');checks.push('output dialog updates and real stdin input reaches shell');await shot('task-output');await click('#closeDialog');
  await until(async()=>/已完成/.test(await js(`document.querySelector('[data-job="${id}"]')?.closest('.job').textContent||''`)),'completed state');checks.push('completion state and exit code update');
  const second=await tool('run_command',{command:'Write-Output "CANCEL_READY"; Start-Sleep -Seconds 60',wait:false});const cancel=second.match(/cmd-\d+/)[0];await until(()=>js(`!!document.querySelector('[data-cancel="${cancel}"]')`),'cancel button');const cancelledPid=require('../core/tools-exec').commands.get(cancel).child.pid;await click(`[data-cancel="${cancel}"]`);await until(async()=>/已停止/.test(await js(`document.querySelector('[data-job="${cancel}"]')?.closest('.job').textContent||''`)),'cancelled state');await until(()=>{try{process.kill(cancelledPid,0);return false;}catch(e){return e.code==='ESRCH';}},'cancelled OS process gone');checks.push('UI cancellation stops actual process and updates state');
  const failed=await tool('run_command',{command:'Write-Output "FAILURE_FIXTURE"; exit 7',wait:false});const fail=failed.match(/cmd-\d+/)[0];await until(async()=>/失败.*退出码 7/s.test(await js(`document.querySelector('[data-job="${fail}"]')?.closest('.job').textContent||''`)),'failure status');checks.push('nonzero exit displayed as failure');await shot('tasks');
  await click('[data-view="history"]');await tool('read_files',{paths:['fixture.txt']});await tool('apply_patch',{file_path:'fixture.txt',edits:[{old_text:'before-flow',new_text:'after-flow'}]});
  await until(()=>js("!!document.querySelector('[data-revision]')"),'history update with case-variant workspace');const revision=await js("document.querySelector('[data-revision]').dataset.revision");assert.equal(fs.readFileSync(path.join(root,'fixture.txt'),'utf8'),'after-flow\n');checks.push('real MCP patch updates history, including Windows path casing');
  await click(`[data-revision="${revision}"]`);await until(async()=>/before-flow/.test(await dom('#detailBody'))&&/after-flow/.test(await dom('#detailBody')),'before/after diff');await shot('change-diff');await click('#closeDialog');checks.push('diff dialog contains actual before and after contents');
  await click(`[data-restore="${revision}"]`);await until(async()=>/已恢复/.test(await js(`document.querySelector('[data-revision="${revision}"]')?.closest('.revision').textContent||''`)),'restore updates history');assert.equal(fs.readFileSync(path.join(root,'fixture.txt'),'utf8'),'before-flow\n');assert(!(await js(`!!document.querySelector('[data-restore="${revision}"]')`)));checks.push('UI restore writes original content and removes restore button');
  await tool('apply_patch',{file_path:'created.txt',content:'created fixture'});await until(async()=>/created.txt/.test(await dom('#historyList')),'created record');const created=(await action('state')).history.find(h=>h.file.endsWith('created.txt'));assert(created);await click(`[data-restore="${created.id}"]`);await until(()=>!fs.existsSync(path.join(root,'created.txt')),'restore creation deletes fixture');checks.push('new-file history and restore update');
  await tool('read_files',{paths:['fixture.txt']});await tool('apply_patch',{file_path:'fixture.txt',content:'remote version'});const conflict=(await action('state')).history.find(h=>!h.restored&&h.file.endsWith('fixture.txt'));fs.writeFileSync(path.join(root,'fixture.txt'),'newer manual edit');await assert.rejects(action('restore',{id:conflict.id}),/changed/);assert.equal(fs.readFileSync(path.join(root,'fixture.txt'),'utf8'),'newer manual edit');checks.push('newer manual content protected from conflicting restore');await shot('history');
  const readOnly=path.join(root,'readonly-fixture.txt');fs.writeFileSync(readOnly,'unchanged readonly');const countBefore=(await action('state')).history.length;
  await tool('read_files',{paths:['readonly-fixture.txt']});fs.chmodSync(readOnly,0o444);
  try{const refused=await rpc('tools/call',{name:'apply_patch',arguments:{file_path:'readonly-fixture.txt',content:'must not appear'}});assert.equal(refused.isError,true);}finally{fs.chmodSync(readOnly,0o666);}
  assert.equal(fs.readFileSync(readOnly,'utf8'),'unchanged readonly');assert.equal((await action('state')).history.length,countBefore);checks.push('real readonly write refusal does not create false history');
  await tool('apply_patch',{file_path:'pending-restore.txt',content:'retain after stop'});const pendingRevision=(await action('state')).history.find(h=>h.file.endsWith('pending-restore.txt'));
  const autoConfirm=dialog.showMessageBox;let answer;dialog.showMessageBox=()=>new Promise(resolve=>{answer=resolve;});const pendingRestore=action('restore',{id:pendingRevision.id});await until(()=>!!answer,'restore confirmation opened');await action('stop');answer({response:1});await assert.rejects(pendingRestore,/连接状态或工作区已变化/);dialog.showMessageBox=autoConfirm;
  assert.equal(fs.readFileSync(path.join(root,'pending-restore.txt'),'utf8'),'retain after stop');assert.equal((await action('state')).history.find(h=>h.id===pendingRevision.id).restored,false);checks.push('stop during restore confirmation prevents stale restore');await action('start');
  const stopping=await tool('run_command',{command:'Start-Sleep -Seconds 60',wait:false});const stoppingId=stopping.match(/cmd-\d+/)[0];const stoppingPid=require('../core/tools-exec').commands.get(stoppingId).child.pid;
  await click('#startStop');await until(()=>!bridge.server,'server stops');await click('[data-view="jobs"]');await until(async()=>/已完成/.test(await dom('#jobsList'))&&/已停止/.test(await dom('#jobsList')),'records retained after connection stop');checks.push('stopping connection retains completed and cancelled tasks');await until(()=>{try{process.kill(stoppingPid,0);return false;}catch(e){return e.code==='ESRCH';}},'connection stop terminates OS process');assert.equal((await action('state')).jobs.find(j=>j.id===stoppingId).cancelled,true);checks.push('connection stop terminates active task and retains stopped record');
  const other=path.join(base,'other-workspace');fs.mkdirSync(other,{recursive:true});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[other]});await until(()=>js("!document.querySelector('#chooseRoot').disabled"),'workspace selector enabled after stop completes');await click('#chooseRoot');await until(async()=>(await action('state')).config.root===fs.realpathSync(other),'workspace switched');await until(async()=>/暂无任务/.test(await dom('#jobsList')),'old tasks cleared');assert.equal((await action('state')).history.length,0);await assert.rejects(action('historyDetail',{id:revision}),/找不到/);checks.push('workspace switch clears tasks and isolates history');
  assert(confirmations.length>=6);assert(confirmations.every(c=>c.title.includes('mcp-bridge')));assert.equal(errors.length,0,errors.join(';'));checks.push('renderer has no unexpected console errors');
  fs.writeFileSync(path.join(base,'flow-result.json'),JSON.stringify({ok:true,packaged:app.isPackaged,version:app.getVersion(),checks,confirmations,confirmationMode:'Isolated test process automatically answers native confirmation API; human interaction not tested'},null,2));console.log('BRIDGE_FLOW_OK '+checks.length);dialog.showMessageBox=original;dialog.showOpenDialog=originalOpen;app.quit();
 }catch(e){dialog.showMessageBox=original;dialog.showOpenDialog=originalOpen;fs.writeFileSync(path.join(base,'flow-result.json'),JSON.stringify({ok:false,checks,error:e.stack},null,2));console.error(e.stack);app.exit(1);}
};
