const fs=require('fs');const path=require('path');const {Worker}=require('worker_threads');const rt=require('./runtime');const scope=require('./scope');const history=require('./history');const schemas=require('./schemas.json');
const MAX=2*1024*1024;
function read(p){p=scope.resolvePath(p);const st=fs.statSync(p);if(!st.isFile()||st.size>MAX)throw Error('Expected a file no larger than 2 MiB');const t=fs.readFileSync(p,'utf8');if(t.includes('\0'))throw Error('Binary file: use read_image when appropriate');return t;}
const handlers={
 read_files:async a=>{if(a.paths.length>20)throw Error('Read at most 20 files per call');let total=0;return a.paths.map(p=>{try{const t=read(p);total+=t.length;if(total>4*MAX)throw Error('Combined read limit exceeded');return `${p}\n${'-'.repeat(60)}\n${t}`;}catch(e){return `${p}\n[ERROR] ${e.message}`;}}).join('\n\n');},
 read_image:async a=>{const p=scope.resolvePath(a.path);const mime={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp'}[path.extname(p).toLowerCase()];if(!mime)throw Error('Unsupported image format');if(fs.statSync(p).size>8*1024*1024)throw Error('Image exceeds 8 MiB');return [{type:'image',mimeType:mime,data:fs.readFileSync(p).toString('base64')}];},
 list_directory:async a=>{const p=scope.resolvePath(a.path||'.');let entries=fs.readdirSync(p,{withFileTypes:true}).filter(e=>a.show_hidden||!e.name.startsWith('.')).sort((a,b)=>Number(b.isDirectory())-Number(a.isDirectory())||a.name.localeCompare(b.name));return `${a.path||'.'}: ${entries.length} entries\n`+entries.slice(0,Math.min(2000,Math.max(1,a.max_entries||300))).map(e=>`[${e.isSymbolicLink()?'link':e.isDirectory()?'dir':'file'}] ${e.name}`).join('\n');},
 find_files:async a=>{const r=await require('./walk').find(a.glob,a.exclude||'',Math.min(1000,Math.max(1,a.max_results||200)));return r.files.map(scope.displayPath).join('\n')+(r.limited?'\n[scan/result limit reached]':'')||'No files matched';},
 search_files:async a=>{if(!a.query||a.query.length>500)throw Error('Search query must contain 1–500 characters');return new Promise((resolve,reject)=>{const w=new Worker(path.join(__dirname,'search-worker.js'),{workerData:{root:scope.primaryRoot(),args:{...a,max_results:Math.min(1000,Math.max(1,a.max_results||200))}}});const timer=setTimeout(()=>{w.terminate();reject(Error('Search exceeded 15 seconds; narrow the pattern'));},15000);w.once('message',r=>{clearTimeout(timer);w.terminate();r&&r.error?reject(Error(r.error)):resolve(r);});w.once('error',e=>{clearTimeout(timer);reject(e);});});},
 apply_patch:async a=>{
  const epoch=rt.epoch;const p=scope.resolvePath(a.file_path);const exists=fs.existsSync(p);const before=exists?read(p):null;let after=before??'';
  if(typeof a.content==='string'&&a.edits)throw Error('Use content OR edits, not both');
  if(typeof a.content==='string')after=a.content;else if(Array.isArray(a.edits)&&a.edits.length){for(const e of a.edits){if(!e.old_text||typeof e.new_text!=='string')throw Error('Each edit requires nonempty old_text and string new_text');const first=after.indexOf(e.old_text);if(first<0||after.indexOf(e.old_text,first+1)>=0)throw Error('old_text must match exactly once; re-read the file');after=after.slice(0,first)+e.new_text+after.slice(first+e.old_text.length);}}else throw Error('Provide content or nonempty edits');
  if(Buffer.byteLength(after)>MAX)throw Error('Updated file exceeds 2 MiB');if(after===before)return 'No changes';
  if(rt.config.editConfirm&&!await rt.confirm({kind:'edit',message:`文件修改申请\n${p}\n\n原内容：\n${(before??'(新文件)').slice(0,3500)}\n\n新内容：\n${after.slice(0,3500)}\n\n内容较长时此确认仅显示开头；完整修改将保存到变更记录。`}))throw Error('[user refused] File was not changed. Do not retry through another tool.');
  if(rt.epoch!==epoch)throw Error('Bridge stopped during review');require('./policy').ensureAllowed('apply_patch');scope.resolvePath(p);if((fs.existsSync(p)?read(p):null)!==before)throw Error('File changed during review. Re-read it first.');
  const id=history.record(p,before,after,()=>{fs.mkdirSync(path.dirname(p),{recursive:true});scope.resolvePath(p);fs.writeFileSync(p,after,'utf8');});rt.changed();return `Updated ${a.file_path}; desktop revision ${id}. Restore is available locally in Change history.`;
 }
};
module.exports={TOOLS:Object.entries(handlers).map(([name,run])=>({...schemas[name],run})),read};
