'use strict';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let current,view='overview',jobId,toastTimer,settingsDirty=false;const labels={overview:'连接控制台',tools:'工具清单',jobs:'运行任务',history:'变更记录',settings:'应用设置'};
function toast(text,error=false){$('#toast').textContent=text;$('#toast').className=error?'error':'';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').className='hidden',4500);}
async function call(action,payload){try{return await window.desktop.call(action,payload);}catch(e){toast(e.message.replace(/^Error invoking remote method '[^']+': Error: /,''),true);return undefined;}}
function switchView(v){view=v;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('hidden',el.id!=='view-'+v));document.querySelectorAll('#nav button').forEach(el=>el.classList.toggle('selected',el.dataset.view===v));$('#pageName').textContent=labels[v];if(v==='settings'&&!settingsDirty)fillSettings();}
function fillSettings(){if(!current)return;const c=current.config;$('#settingPort').value=c.port;$('#settingTunnel').value=c.tunnelProvider;for(const [id,key]of [['EditConfirm','editConfirm'],['CommandConfirm','commandConfirm'],['ScreenshotConfirm','screenshotConfirm'],['CloseToTray','closeToTray']])$('#setting'+id).checked=!!c[key];$('#settingDotnet').value=c.dotnetPath||'';$('#settingGodot').value=c.godotPath||'';$('#settingInstructions').value=c.extraInstructions||'';}
function renderTools(){if(!current)return;const q=$('#toolSearch').value.toLowerCase();$('#toolsGrid').innerHTML=current.tools.filter(t=>(t.name+' '+t.description).toLowerCase().includes(q)).map(t=>{const enabled=!t.capability||current.config.permissions[t.capability];return `<article class="tool"><header><code>${esc(t.name)}</code><span class="pill ${enabled?'':'off'}">${t.capability?esc(t.capability):'计划'} · ${enabled?'已启用':'未授权'}</span></header><p>${esc(t.description)}</p></article>`;}).join('');}
function render(s){if(!s?.config)return;current=s;const running=s.running;const title=s.busy?'正在连接 / 处理…':running?'已连接':'未连接';$('#statusBadge').textContent=title;$('#statusBadge').className='badge'+(running?' on':'');$('#statConnection').textContent=running?'在线':'离线';$('#statMode').textContent=s.publicUrl?'公网隧道已就绪':'仅本地连接';$('#statTools').innerHTML=s.tools.length+'<em> 个</em>';$('#toolCount').textContent=s.tools.length;$('#statJobs').innerHTML=s.jobs.filter(j=>j.running).length+'<em> 项任务</em>';$('#statCalls').innerHTML=s.activities.length+'<em> 次</em>';$('#workspacePath').textContent=s.config.root||'尚未选择工作目录';$('#workspacePath').title=s.config.root||'';$('#chooseRoot').disabled=running||s.busy;$('#connectionUrl').value=s.publicUrl||s.localUrl;$('#connectionMode').textContent=s.config.tunnelProvider==='none'?'仅本地 · 127.0.0.1':'Cloudflare · 临时公网连接';$('#startStop').textContent=s.busy?'处理中…':running?'■ 停止连接':'▶ 启动连接';$('#startStop').className='primary'+(running?' danger':'');$('#startStop').disabled=s.busy||(!running&&!s.config.root);for(const id of ['copyUrl','copyPrompt','guide','testConnection'])$('#'+id).disabled=!running;$('#footerStatus').textContent=title;$('#sideStatus').innerHTML=`<i${running?' class="on-dot"':''}></i>${running?'服务正在运行':'服务未启动'}`;$('#version').textContent='mcp-bridge '+s.version;
 const note=s.tunnelError||(s.tunnelStatus==='connecting'?'正在建立公网隧道，本地连接已就绪…':'');$('#tunnelNote').textContent=note;$('#tunnelNote').classList.toggle('hidden',!note);
 const permissions=[['read','读取文件','查看目录、文件和图片','▱'],['edit','修改文件','精确修改，可查看与恢复','✎'],['execute','执行命令','运行程序与构建任务','⌘'],['capture','截取屏幕','分享桌面或窗口画面','▣']];$('#permissionList').innerHTML=permissions.map(([id,title,desc,icon])=>`<div class="permission-row"><div class="permission-icon">${icon}</div><div class="permission-copy"><strong>${title}</strong><span>${desc}</span></div><button class="switch ${s.config.permissions[id]?'on':''}" data-permission="${id}" role="switch" aria-checked="${s.config.permissions[id]}" aria-label="${title}"></button></div>`).join('');
 $('#progressEmpty').classList.toggle('hidden',!!(s.progress||s.todos.length));$('#progressContent').classList.toggle('hidden',!(s.progress||s.todos.length));$('#progressMessage').textContent=s.progress?.message||'任务计划';$('#progressBar').style.width=(s.progress?.percent??0)+'%';$('#todoList').innerHTML=s.todos.map(t=>`<li><span class="${t.status==='completed'?'ok':'muted'}">${t.status==='completed'?'✓':t.status==='in_progress'?'◉':'○'}</span>${esc(t.title)}</li>`).join('');
 $('#activityList').className=s.activities.length?'':'empty';$('#activityList').innerHTML=s.activities.length?s.activities.slice(0,8).map(a=>`<div class="activity-row"><span class="muted">${new Date(a.time).toLocaleTimeString('zh-CN',{hour12:false})}</span><code>${esc(a.name)}</code><span class="${a.ok?'ok':'fail'}">${a.ok?'已完成':'未完成'}</span><span class="muted">${a.ms} ms</span></div>`).join(''):'<span>↗</span><p>还没有工具调用。连接后的操作会显示在这里。</p>';
 $('#jobsList').innerHTML=s.jobs.length?s.jobs.map(j=>`<article class="job"><span class="badge ${j.running?'on':''}">${j.running?'运行中':j.cancelled?'已停止':j.exitCode===0?'已完成':'失败'}</span><div class="job-info"><code>${esc(j.command)}</code><small>${esc(j.id)} · ${j.running?'后台执行':'退出码 '+j.exitCode} · ${esc(j.cwd)}</small></div><button class="secondary" data-job="${esc(j.id)}">查看输出</button>${j.running?`<button class="secondary fail" data-cancel="${esc(j.id)}">停止</button>`:''}</article>`).join(''):'<div class="card empty"><span>⌘</span><p>暂无任务。AI 执行的命令会出现在这里。</p></div>';
 $('#historyList').innerHTML=s.history.length?s.history.map(h=>`<article class="revision"><span class="permission-icon">↶</span><div class="revision-info"><code>${esc(h.file)}</code><small>${new Date(h.time).toLocaleString('zh-CN')} · ${h.restored?'已恢复':h.unverified?'写入结果待核实 · 请查看备份':h.failed?'写入未完成 · 可查看与恢复':h.kind==='created'?'新建文件':'修改文件'}</small></div><button class="secondary" data-revision="${esc(h.id)}">查看差异</button>${!h.restored&&!h.unverified?`<button class="secondary" data-restore="${esc(h.id)}">恢复</button>`:''}</article>`).join(''):'<div class="card empty"><span>↶</span><p>暂无文件变更。请选择工作目录，开始协作。</p></div>';
 if(jobId){const alive=!!s.jobs.find(j=>j.id===jobId&&j.running);$('#sendInput').disabled=!alive;$('#jobInput').disabled=!alive;}
 renderTools();if(!settingsDirty&&view==='settings')fillSettings();$('#settingPort').disabled=running;$('#settingTunnel').disabled=running;$('#rotateToken').disabled=running||s.busy;
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)switchView(b.dataset.view);if(b.dataset.goto)switchView(b.dataset.goto);if(b.dataset.permission)await call('settings',{permissions:{[b.dataset.permission]:!current.config.permissions[b.dataset.permission]}});if(b.dataset.cancel)await call('cancelJob',{id:b.dataset.cancel});if(b.dataset.job){jobId=b.dataset.job;const text=await call('jobOutput',{id:jobId});if(text!==undefined){$('#detailTitle').textContent='任务输出 · '+jobId;$('#detailBody').innerHTML='<pre id="liveJobOutput">'+esc(text)+'</pre>';$('#jobInputBox').classList.remove('hidden');const alive=!!current.jobs.find(j=>j.id===jobId&&j.running);$('#sendInput').disabled=!alive;$('#jobInput').disabled=!alive;$('#detailDialog').showModal();}}if(b.dataset.revision){const h=await call('historyDetail',{id:b.dataset.revision});if(h){jobId=null;$('#detailTitle').textContent='变更记录';$('#detailBody').innerHTML=`<p class="muted">${esc(h.file)}</p><div class="revision-diff"><div><h3>修改之前</h3><pre>${esc(h.before??'(新文件)')}</pre></div><div><h3>修改之后</h3><pre>${esc(h.after)}</pre></div></div>`;$('#jobInputBox').classList.add('hidden');$('#detailDialog').showModal();}}if(b.dataset.restore){if(await call('restore',{id:b.dataset.restore}))toast('文件已恢复');}});
$('#chooseRoot').onclick=()=>call('chooseRoot');$('#startStop').onclick=()=>call(current.running?'stop':'start');$('#copyUrl').onclick=async()=>{if(await call('copyUrl',{public:!!current.publicUrl}))toast('连接地址已复制，请勿公开分享');};$('#copyPrompt').onclick=async()=>{if(await call('copyPrompt'))toast('接入提示词已复制');};$('#guide').onclick=()=>call('guide');$('#testConnection').onclick=async()=>{const r=await call('testConnection');if(r)toast(`握手成功，${r.count} 个工具可发现`);};$('#revealUrl').onclick=()=>{const show=$('#connectionUrl').type==='password';$('#connectionUrl').type=show?'text':'password';$('#revealUrl').textContent=show?'隐藏凭据':'显示凭据';};$('#clearActivity').onclick=()=>call('clearActivity');$('#toolSearch').oninput=renderTools;$('#closeDialog').onclick=()=>{$('#detailDialog').close();jobId=null;};$('#sendInput').onclick=async()=>{if(await call('jobInput',{id:jobId,input:$('#jobInput').value})){$('#jobInput').value='';toast('输入已发送');}};
$('#settingsForm').oninput=()=>settingsDirty=true;$('#settingsForm').onsubmit=async e=>{e.preventDefault();const p={commandConfirm:$('#settingCommandConfirm').checked,screenshotConfirm:$('#settingScreenshotConfirm').checked,editConfirm:$('#settingEditConfirm').checked,closeToTray:$('#settingCloseToTray').checked,dotnetPath:$('#settingDotnet').value.trim(),godotPath:$('#settingGodot').value.trim(),extraInstructions:$('#settingInstructions').value};if(!current.running){p.port=Number($('#settingPort').value);p.tunnelProvider=$('#settingTunnel').value;}if(await call('settings',p)){settingsDirty=false;toast('设置已保存');}};$('#rotateToken').onclick=async()=>{if(await call('rotateToken'))toast('连接凭据已更换，旧链接不再有效');};
window.desktop.subscribe(render);call('state').then(render);
let outputPolling=false;
setInterval(async()=>{
 if(outputPolling||!jobId||!$('#detailDialog').open)return;
 const requestedId=jobId;outputPolling=true;
 try{const text=await call('jobOutput',{id:requestedId});const pre=$('#liveJobOutput');
  if(text!==undefined&&pre&&jobId===requestedId&&$('#detailDialog').open){const top=pre.scrollTop;const follow=pre.scrollHeight-pre.clientHeight-top<36;pre.textContent=text;pre.scrollTop=follow?pre.scrollHeight:top;}
 }finally{outputPolling=false;}
},700);
